export enum Identifiers {
	EMAIL = "EMAIL",
	PASSWORD = "PASSWORD",
	PASSWORD_VALIDATION = "PASSWORD_VALIDATION",
	REFERRAL_CODE = 'REFERRAL_CODE',
	REFERRAL_CODE_VALIDATION = 'REFERRAL_CODE_VALIDATION',
	ACCOUNT_CREATION = 'ACCOUNT_CREATION',
}