export enum Identifiers {
	ACCOUNT_TYPE = "ACCOUNT_TYPE",
	INDIVIDUAL_NAME = "INDIVIDUAL_NAME",
	INDIVIDUAL_COLOR = 'INDIVIDUAL_COLOR',
	INDIVIDUAL_TIME = 'INDIVIDUAL_TIME',
	INDIVIDUAL_VALIDATION = 'INDIVIDUAL_VALIDATION',
	CORPORATE_COMPANY_NAME = "CORPORATE_COMPANY_NAME",
	CORPORATE_EMPLOYEES = "CORPORATE_EMPLOYEES",
	CORPORATE_INDUSTRY = "CORPORATE_INDUSTRY",
	CORPORATE_VALIDATION = 'CORPORATE_VALIDATION',
}